name: 'Metrics'
on:
  # Schedule updates (each hour)
  schedule:
    - cron: "* */24 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'lowlighter/metrics@latest'
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - public_repo
          #  - read:project
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: '${{ secrets.PROFILE_READ_PAT }}'
          user: 'jamashita'
          template: 'classic'
          plugin_isocalendar: 'yes'
          plugin_isocalendar_duration: 'full-year'
          plugin_languages: 'yes'
          plugin_languages_analysis_timeout: '15'
          plugin_languages_colors: 'github'
