name: 'Waka Readme'
on:
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: 'Update Readme with Metrics'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Generate wakatime report'
        uses: 'anmol098/waka-readme-stats@master'
        with:
          WAKATIME_API_KEY: '${{ secrets.WAKATIME_API_KEY }}'
          GH_TOKEN: '${{ secrets.WAKATIME_PAT }}'
